apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: uni
  namespace: argocd
spec:
  description: "Apps managed via GitOps for uni-test-task"
  sourceRepos:
    - "https://github.com/alakaganaguathoork/uni-test-task.git"

  destinations:
    - namespace: '!kube-system'
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: vmstack
      server: https://kubernetes.default.svc
    - namespace: app
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  # namespaceResourceWhitelist:
    # - group: "*"
      # kind: "*"

  orphanedResources:
    warn: true
