{
 "title": "Spam2000",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "App Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"spam\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total by country filtered by (\"Ukraine|Afghanistan)\"",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(random_gauge_1{country=~\"(Ukraine|Afghanistan)\"}) by (country)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Values distributed into buckets over time by `le`",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (le) (\n  rate(random_histogram_bucket[5m])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95th percentile (p95) value of random_histogram over time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(random_histogram_bucket[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}